//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt_Poig.Properties.Lang {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Projekt_Poig.Properties.Lang.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu ------------------------------------------------------------------------------------------------------------------------------.
        /// </summary>
        public static string ___________________________________________________________ {
            get {
                return ResourceManager.GetString("-----------------------------------------------------------", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu ----------------------------------------------------------------------------------------------------------------------------.
        /// </summary>
        public static string ____________________________________________________________ {
            get {
                return ResourceManager.GetString("------------------------------------------------------------", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu ----------------------------------------------------------------------------------------------------------------------------------------------------------------.
        /// </summary>
        public static string ___________________________________________________________________________________________________ {
            get {
                return ResourceManager.GetString("---------------------------------------------------------------------------------" +
                        "------------------", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Add.
        /// </summary>
        public static string ADD {
            get {
                return ResourceManager.GetString("ADD", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Singleplayer.
        /// </summary>
        public static string AT_Attribute_1 {
            get {
                return ResourceManager.GetString("AT_Attribute_1", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Puzzle.
        /// </summary>
        public static string AT_Attribute_10 {
            get {
                return ResourceManager.GetString("AT_Attribute_10", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Simulation.
        /// </summary>
        public static string AT_Attribute_11 {
            get {
                return ResourceManager.GetString("AT_Attribute_11", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Horror.
        /// </summary>
        public static string AT_Attribute_12 {
            get {
                return ResourceManager.GetString("AT_Attribute_12", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Adventure.
        /// </summary>
        public static string AT_Attribute_13 {
            get {
                return ResourceManager.GetString("AT_Attribute_13", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Multiplayer.
        /// </summary>
        public static string AT_Attribute_2 {
            get {
                return ResourceManager.GetString("AT_Attribute_2", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu FPS.
        /// </summary>
        public static string AT_Attribute_3 {
            get {
                return ResourceManager.GetString("AT_Attribute_3", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Open World.
        /// </summary>
        public static string AT_Attribute_4 {
            get {
                return ResourceManager.GetString("AT_Attribute_4", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Storyline.
        /// </summary>
        public static string AT_Attribute_5 {
            get {
                return ResourceManager.GetString("AT_Attribute_5", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Strategy.
        /// </summary>
        public static string AT_Attribute_6 {
            get {
                return ResourceManager.GetString("AT_Attribute_6", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu RPG.
        /// </summary>
        public static string AT_Attribute_7 {
            get {
                return ResourceManager.GetString("AT_Attribute_7", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Roguelike.
        /// </summary>
        public static string AT_Attribute_8 {
            get {
                return ResourceManager.GetString("AT_Attribute_8", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Action.
        /// </summary>
        public static string AT_Attribute_9 {
            get {
                return ResourceManager.GetString("AT_Attribute_9", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu From :.
        /// </summary>
        public static string AT_From {
            get {
                return ResourceManager.GetString("AT_From", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu ID Game.
        /// </summary>
        public static string AT_idGame {
            get {
                return ResourceManager.GetString("AT_idGame", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu To :.
        /// </summary>
        public static string AT_To {
            get {
                return ResourceManager.GetString("AT_To", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu SUCCESSFULLY ADDED ATTRIBUTE!.
        /// </summary>
        public static string Atr_Add {
            get {
                return ResourceManager.GetString("Atr_Add", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu SUCCESSFULLY DELETED ATTRIBUTE!.
        /// </summary>
        public static string Atr_Del {
            get {
                return ResourceManager.GetString("Atr_Del", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu SUCCESSFULLY EDITED ATTRIBUTE!.
        /// </summary>
        public static string Atr_Edit {
            get {
                return ResourceManager.GetString("Atr_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu YOU CANNOT DELETE THIS GAME!.
        /// </summary>
        public static string BUG_1 {
            get {
                return ResourceManager.GetString("BUG_1", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu YOU CANNOT DELETE THIS PLAYER TYPE!.
        /// </summary>
        public static string BUG_2 {
            get {
                return ResourceManager.GetString("BUG_2", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Delete.
        /// </summary>
        public static string DELETE {
            get {
                return ResourceManager.GetString("DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Change language.
        /// </summary>
        public static string DP_Change {
            get {
                return ResourceManager.GetString("DP_Change", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu English.
        /// </summary>
        public static string DP_LangName {
            get {
                return ResourceManager.GetString("DP_LangName", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Edit.
        /// </summary>
        public static string EDIT {
            get {
                return ResourceManager.GetString("EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu flag_dif.
        /// </summary>
        public static string Flag {
            get {
                return ResourceManager.GetString("Flag", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu SUCCESSFULLY ADDED GAME!.
        /// </summary>
        public static string Gry_Add {
            get {
                return ResourceManager.GetString("Gry_Add", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu SUCCESSFULLY DELETED GAME!.
        /// </summary>
        public static string Gry_Del {
            get {
                return ResourceManager.GetString("Gry_Del", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu SUCCESSFULLY EDITED GAME!.
        /// </summary>
        public static string Gry_Edit {
            get {
                return ResourceManager.GetString("Gry_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Game name:.
        /// </summary>
        public static string GT_Game_ {
            get {
                return ResourceManager.GetString("GT_Game:", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu ID Game.
        /// </summary>
        public static string GT_idGame {
            get {
                return ResourceManager.GetString("GT_idGame", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu ID Type.
        /// </summary>
        public static string GT_idType {
            get {
                return ResourceManager.GetString("GT_idType", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Game Name.
        /// </summary>
        public static string GT_Name {
            get {
                return ResourceManager.GetString("GT_Name", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Player name:.
        /// </summary>
        public static string GT_Player_ {
            get {
                return ResourceManager.GetString("GT_Player:", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Game Database.
        /// </summary>
        public static string MW_Application {
            get {
                return ResourceManager.GetString("MW_Application", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Attributes.
        /// </summary>
        public static string MW_Attributes {
            get {
                return ResourceManager.GetString("MW_Attributes", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Games.
        /// </summary>
        public static string MW_Game {
            get {
                return ResourceManager.GetString("MW_Game", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Types.
        /// </summary>
        public static string MW_Type {
            get {
                return ResourceManager.GetString("MW_Type", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Game&apos;s Types.
        /// </summary>
        public static string MW_TypeView {
            get {
                return ResourceManager.GetString("MW_TypeView", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Search:.
        /// </summary>
        public static string SEARCH {
            get {
                return ResourceManager.GetString("SEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Add.
        /// </summary>
        public static string TT_Button {
            get {
                return ResourceManager.GetString("TT_Button", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Description.
        /// </summary>
        public static string TT_Description {
            get {
                return ResourceManager.GetString("TT_Description", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu ID Player.
        /// </summary>
        public static string TT_idGame {
            get {
                return ResourceManager.GetString("TT_idGame", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Player Type.
        /// </summary>
        public static string TT_Player {
            get {
                return ResourceManager.GetString("TT_Player", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Player description:.
        /// </summary>
        public static string TT_PlayerDesc {
            get {
                return ResourceManager.GetString("TT_PlayerDesc", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Player Name.
        /// </summary>
        public static string TT_PlayerName {
            get {
                return ResourceManager.GetString("TT_PlayerName", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu SUCCESSFULLY ADDED PLAYER TYPE!.
        /// </summary>
        public static string Typ_Add {
            get {
                return ResourceManager.GetString("Typ_Add", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu SUCCESSFULLY DELETED PLAYER TYPE!.
        /// </summary>
        public static string Typ_Del {
            get {
                return ResourceManager.GetString("Typ_Del", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu SUCCESSFULLY EDITED PLAYER TYPE!.
        /// </summary>
        public static string Typ_Edit {
            get {
                return ResourceManager.GetString("Typ_Edit", resourceCulture);
            }
        }
    }
}
